Początek programu
**pogrubiony tekst** \
Nowa linia
# Nowa sekcja
## Nowa sekcja
### Nowa sekcja

In [1]:
print("Witaj w notatniku...")

Witaj w notatniku...


In [2]:
a = 5
b = 6

In [3]:
print(a, b)

5 6


In [ ]:
c = 9

In [4]:
print(c)

NameError: name 'c' is not defined

In [6]:
a

5

# Bibliotek NumPy

Napisana w jęzuku C do szybkich operacji na danych tablicowych\
podstawowy element: **ndarray**

In [7]:
# !pip install numpy
!pip install numpy==2.0.2

   ---------------------------------------- 0.0/15.6 MB ? eta -:--:--
   ------------------- -------------------- 7.6/15.6 MB 67.3 MB/s eta 0:00:01
   ---------------------------------------- 15.6/15.6 MB 49.2 MB/s eta 0:00:00



[notice] A new release of pip is available: 25.1.1 -> 25.2
[notice] To update, run: python.exe -m pip install --upgrade pip


In [8]:
!pip list

Package                   Version
------------------------- --------------
anyio                     4.10.0
argon2-cffi               25.1.0
argon2-cffi-bindings      25.1.0
arrow                     1.3.0
asttokens                 3.0.0
async-lru                 2.0.5
attrs                     25.3.0
babel                     2.17.0
beautifulsoup4            4.13.5
bleach                    6.2.0
certifi                   2025.8.3
cffi                      1.17.1
charset-normalizer        3.4.3
colorama                  0.4.6
comm                      0.2.3
debugpy                   1.8.16
decorator                 5.2.1
defusedxml                0.7.1
executing                 2.2.0
fastjsonschema            2.21.2
fqdn                      1.5.1
h11                       0.16.0
httpcore                  1.0.9
httpx                     0.28.1
idna                      3.10
ipykernel                 6.30.1
ipython                   9.4.0
ipython_pygments_lexers   1.1.1
isoduration    

In [10]:
import numpy as np

In [11]:
lista = [2, 4, 6, 8, 10]
print(lista)
lista

[2, 4, 6, 8, 10]


[2, 4, 6, 8, 10]

In [13]:
a = np.array(lista)
print(a)
a

[ 2  4  6  8 10]


array([ 2,  4,  6,  8, 10])

In [14]:
print(type(a))

<class 'numpy.ndarray'>


In [15]:
print(a.dtype)

int64


int64 - 8 bajtów\
posiada konkretny zakres

In [16]:
print(a.shape)  # kształt tablicy

(5,)


In [17]:
p = np.zeros((3, 3))  # tablica z zerami
p

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [18]:
print(p.dtype)

float64


float64 - 8bitów

In [19]:
q = np.ones((2, 2))  # tablica jedynek
print(q)
q.dtype

[[1. 1.]
 [1. 1.]]


dtype('float64')

In [20]:
r = np.full((2, 2), 4)  # tablica wypełniona czwórkami
print(r)
r.dtype

[[4 4]
 [4 4]]


dtype('int64')

In [21]:
s = np.eye(4)  # umieszczenie po przekątnej
print(s)
s.dtype

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


dtype('float64')

In [22]:
t = np.random.random((3, 3))
print(t)
t.dtype

[[0.03741016 0.84117417 0.22647729]
 [0.39379369 0.5665942  0.30664526]
 [0.55859361 0.54118377 0.8123615 ]]


dtype('float64')

In [23]:
lista2 = [[5, 6], [7, 8]]
print(lista2)

[[5, 6], [7, 8]]


In [24]:
b = np.array(lista2)
print(b)

[[5 6]
 [7 8]]


In [25]:
# ravel() - spłaszczenie, zwraca nowy obiekt
print(b.ravel())

[5 6 7 8]


In [26]:
print(b[0])

[5 6]


In [27]:
print(b[0, 0])
print(b[0, 1])

5
6


In [28]:
print(np.float64(21))

21.0


In [29]:
print(np.int64(22.0))

22


In [31]:
print(np.bool(21))

True


In [32]:
print(np.float64(True))

1.0


In [34]:
arr = np.arange(1, 11, dtype=np.float64)  # z prawej zbiór otwarty
print(arr)

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]


In [35]:
arr.dtype

dtype('float64')

In [36]:
# reshape() - zmiana kształtu
arr = np.arange(12)
print(arr)

[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [37]:
new_arr = arr.reshape(4, 3)
new_arr

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [39]:
new_arr = arr.reshape(3, 4)
new_arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [40]:
new_arr = arr.reshape(3, 5)
new_arr

ValueError: cannot reshape array of size 12 into shape (3,5)

In [41]:
new_arr = arr.reshape(3, 3)
new_arr

ValueError: cannot reshape array of size 12 into shape (3,3)

ravel() - zwraca widok \
operacja na widoku "tablicy" wpłynie na zmiany oryginalnej tablicy

In [42]:
print(new_arr.ravel())

[ 0  1  2  3  4  5  6  7  8  9 10 11]


flatten() - spłąszcza ale robi kopię\
zmiany nie wpływają na oryginalną tablicę

In [43]:
print(new_arr.flatten())

[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [44]:
flat = new_arr.flatten()
rav = new_arr.ravel()

In [45]:
flat[0] = 999
rav[1] = 888

In [47]:
print(new_arr)  # oryginalna tablica została zmieniona, rav zamienił element

[[  0 888   2   3]
 [  4   5   6   7]
 [  8   9  10  11]]


transpose() - zamienia osie


In [48]:
print(new_arr.transpose())

[[  0   4   8]
 [888   5   9]
 [  2   6  10]
 [  3   7  11]]


resize() - zmienia rozmiar tablicy\
zmienia oryginalną tablicę (in-plce)\
brakujące elementy uzupełnia zerami

In [49]:
new_arr.resize(1, 12)
print(new_arr)

[[  0 888   2   3   4   5   6   7   8   9  10  11]]


In [50]:
arr1 = np.arange(1, 10).reshape(3, 3)
print(arr1)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [51]:
print(np.__version__)

2.0.2


**Broadcasting** \
wykonuje operacje na wszystkich elementach macierzy

In [52]:
lista = [1, 2, 3]
print(2 * lista)

[1, 2, 3, 1, 2, 3]


In [53]:
# przykłąd broadcastingu w numpy
arr2 = 2 * arr1
print(arr2)

[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]


In [55]:
arrx = arr1 + arr2
print(arrx)

[[ 3  6  9]
 [12 15 18]
 [21 24 27]]


### Zasady broadcastingu
wymiary muszą byc zgodne
1. Dwa wymiary są zgodne jeśli:
    sa równe, lub
    jeden z nich ma rozmiar 1
2. Jeśli nie spełniają tych warunków -> ValueError