Początek programu
**pogrubiony tekst** \
Nowa linia
# Nowa sekcja
## Nowa sekcja
### Nowa sekcja

In [1]:
print("Witaj w notatniku...")

Witaj w notatniku...


In [2]:
a = 5
b = 6

In [3]:
print(a, b)

5 6


In [ ]:
c = 9

In [4]:
print(c)

NameError: name 'c' is not defined

In [6]:
a

5

# Bibliotek NumPy

Napisana w jęzuku C do szybkich operacji na danych tablicowych\
podstawowy element: **ndarray**

In [7]:
# !pip install numpy
!pip install numpy==2.0.2

   ---------------------------------------- 0.0/15.6 MB ? eta -:--:--
   ------------------- -------------------- 7.6/15.6 MB 67.3 MB/s eta 0:00:01
   ---------------------------------------- 15.6/15.6 MB 49.2 MB/s eta 0:00:00



[notice] A new release of pip is available: 25.1.1 -> 25.2
[notice] To update, run: python.exe -m pip install --upgrade pip


In [8]:
!pip list

Package                   Version
------------------------- --------------
anyio                     4.10.0
argon2-cffi               25.1.0
argon2-cffi-bindings      25.1.0
arrow                     1.3.0
asttokens                 3.0.0
async-lru                 2.0.5
attrs                     25.3.0
babel                     2.17.0
beautifulsoup4            4.13.5
bleach                    6.2.0
certifi                   2025.8.3
cffi                      1.17.1
charset-normalizer        3.4.3
colorama                  0.4.6
comm                      0.2.3
debugpy                   1.8.16
decorator                 5.2.1
defusedxml                0.7.1
executing                 2.2.0
fastjsonschema            2.21.2
fqdn                      1.5.1
h11                       0.16.0
httpcore                  1.0.9
httpx                     0.28.1
idna                      3.10
ipykernel                 6.30.1
ipython                   9.4.0
ipython_pygments_lexers   1.1.1
isoduration    

In [10]:
import numpy as np

In [11]:
lista = [2, 4, 6, 8, 10]
print(lista)
lista

[2, 4, 6, 8, 10]


[2, 4, 6, 8, 10]

In [13]:
a = np.array(lista)
print(a)
a

[ 2  4  6  8 10]


array([ 2,  4,  6,  8, 10])

In [14]:
print(type(a))

<class 'numpy.ndarray'>


In [15]:
print(a.dtype)

int64


int64 - 8 bajtów\
posiada konkretny zakres

In [16]:
print(a.shape)  # kształt tablicy

(5,)


In [17]:
p = np.zeros((3, 3))  # tablica z zerami
p

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [18]:
print(p.dtype)

float64


float64 - 8bitów

In [19]:
q = np.ones((2, 2))  # tablica jedynek
print(q)
q.dtype

[[1. 1.]
 [1. 1.]]


dtype('float64')

In [20]:
r = np.full((2, 2), 4)  # tablica wypełniona czwórkami
print(r)
r.dtype

[[4 4]
 [4 4]]


dtype('int64')

In [21]:
s = np.eye(4)  # umieszczenie po przekątnej
print(s)
s.dtype

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


dtype('float64')

In [22]:
t = np.random.random((3, 3))
print(t)
t.dtype

[[0.03741016 0.84117417 0.22647729]
 [0.39379369 0.5665942  0.30664526]
 [0.55859361 0.54118377 0.8123615 ]]


dtype('float64')

In [23]:
lista2 = [[5, 6], [7, 8]]
print(lista2)

[[5, 6], [7, 8]]


In [24]:
b = np.array(lista2)
print(b)

[[5 6]
 [7 8]]


In [25]:
# ravel() - spłaszczenie, zwraca nowy obiekt
print(b.ravel())

[5 6 7 8]


In [26]:
print(b[0])

[5 6]


In [27]:
print(b[0, 0])
print(b[0, 1])

5
6


In [28]:
print(np.float64(21))

21.0


In [29]:
print(np.int64(22.0))

22


In [31]:
print(np.bool(21))

True


In [32]:
print(np.float64(True))

1.0


In [34]:
arr = np.arange(1, 11, dtype=np.float64)  # z prawej zbiór otwarty
print(arr)

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]


In [35]:
arr.dtype

dtype('float64')

In [36]:
# reshape() - zmiana kształtu
arr = np.arange(12)
print(arr)

[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [37]:
new_arr = arr.reshape(4, 3)
new_arr

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [39]:
new_arr = arr.reshape(3, 4)
new_arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [40]:
new_arr = arr.reshape(3, 5)
new_arr

ValueError: cannot reshape array of size 12 into shape (3,5)

In [41]:
new_arr = arr.reshape(3, 3)
new_arr

ValueError: cannot reshape array of size 12 into shape (3,3)

ravel() - zwraca widok \
operacja na widoku "tablicy" wpłynie na zmiany oryginalnej tablicy

In [42]:
print(new_arr.ravel())

[ 0  1  2  3  4  5  6  7  8  9 10 11]


flatten() - spłąszcza ale robi kopię\
zmiany nie wpływają na oryginalną tablicę

In [43]:
print(new_arr.flatten())

[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [44]:
flat = new_arr.flatten()
rav = new_arr.ravel()

In [45]:
flat[0] = 999
rav[1] = 888

In [47]:
print(new_arr)  # oryginalna tablica została zmieniona, rav zamienił element

[[  0 888   2   3]
 [  4   5   6   7]
 [  8   9  10  11]]


transpose() - zamienia osie


In [48]:
print(new_arr.transpose())

[[  0   4   8]
 [888   5   9]
 [  2   6  10]
 [  3   7  11]]


resize() - zmienia rozmiar tablicy\
zmienia oryginalną tablicę (in-plce)\
brakujące elementy uzupełnia zerami

In [49]:
new_arr.resize(1, 12)
print(new_arr)

[[  0 888   2   3   4   5   6   7   8   9  10  11]]


In [50]:
arr1 = np.arange(1, 10).reshape(3, 3)
print(arr1)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [51]:
print(np.__version__)

2.0.2


**Broadcasting** \
wykonuje operacje na wszystkich elementach macierzy

In [52]:
lista = [1, 2, 3]
print(2 * lista)

[1, 2, 3, 1, 2, 3]


In [53]:
# przykłąd broadcastingu w numpy
arr2 = 2 * arr1
print(arr2)

[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]


In [55]:
arrx = arr1 + arr2
print(arrx)

[[ 3  6  9]
 [12 15 18]
 [21 24 27]]


### Zasady broadcastingu
wymiary muszą byc zgodne
1. Dwa wymiary są zgodne jeśli:
    sa równe, lub
    jeden z nich ma rozmiar 1
2. Jeśli nie spełniają tych warunków -> ValueError

---------
hstack() - skleja tablice poziomo

In [58]:
arr3 = np.hstack((arr1, arr2))
print(arr3)

[[ 1  2  3  2  4  6]
 [ 4  5  6  8 10 12]
 [ 7  8  9 14 16 18]]


vstack() - skleja pionowo

In [59]:
arr4 = np.vstack((arr1, arr2))
print(arr4)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [ 2  4  6]
 [ 8 10 12]
 [14 16 18]]


concatenate() - sklejanie w wybranej osi

In [60]:
arr5 = np.concatenate((arr1, arr2), axis=0)  # wiersze
print(arr5)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [ 2  4  6]
 [ 8 10 12]
 [14 16 18]]


In [61]:
arr6 = np.concatenate((arr1, arr2), axis=1)  # kolumny
print(arr6)

[[ 1  2  3  2  4  6]
 [ 4  5  6  8 10 12]
 [ 7  8  9 14 16 18]]


Tworzy tablicę z sekwencji

In [62]:
arre1 = np.array([1, 2, 3])
print(arre1)

[1 2 3]


In [63]:
arre2 = np.array([4, 5, 6])
print(arre2)

[4 5 6]


In [66]:
np.concatenate((arre1, arre2), axis=0)

array([1, 2, 3, 4, 5, 6])

In [65]:
np.concatenate((arre1, arre2), axis=1)

AxisError: axis 1 is out of bounds for array of dimension 1

In [68]:
print(arre1)
print(arre1.shape)

[1 2 3]
(3,)


In [69]:
print(arre2)
print(arre2.shape)

[4 5 6]
(3,)


dstack() - skleja tablice w głąb, dodaje trzeci wymiar

In [70]:
arr7 = np.dstack((arr1, arr2))
print(arr7)

[[[ 1  2]
  [ 2  4]
  [ 3  6]]

 [[ 4  8]
  [ 5 10]
  [ 6 12]]

 [[ 7 14]
  [ 8 16]
  [ 9 18]]]


column_stack() - skleja jako kolumny

In [73]:
arr8 = np.arange(4, 7)
print(arr8)
arr9 = 2 * arr8
print(arr9)

arr_col_stack = np.column_stack((arr8, arr9))
print(arr_col_stack)

[4 5 6]
[ 8 10 12]
[[ 4  8]
 [ 5 10]
 [ 6 12]]


row_stack() - jako wiersze

In [74]:
arr_row_stack = np.row_stack((arr8, arr9))
print(arr_row_stack)

[[ 4  5  6]
 [ 8 10 12]]


C:\Users\CSComarch\AppData\Local\Temp\ipykernel_5600\2282068895.py:1: DeprecationWarning: `row_stack` alias is deprecated. Use `np.vstack` directly.
  arr_row_stack = np.row_stack((arr8, arr9))


In [75]:
result_vstack = np.vstack((arr8, arr9))
print(result_vstack)

[[ 4  5  6]
 [ 8 10 12]]


hsplit() - dzieli w poziomie

In [76]:
arr10 = np.arange(1, 10).reshape(3, 3)
print(arr10)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [77]:
arr_split = np.hsplit(arr10, 3)
print(arr_split)

[array([[1],
       [4],
       [7]]), array([[2],
       [5],
       [8]]), array([[3],
       [6],
       [9]])]


vsplit()  - dzieli na wiersze

In [78]:
arr_v_split = np.vsplit(arr10, 3)
print(arr_v_split)

[array([[1, 2, 3]]), array([[4, 5, 6]]), array([[7, 8, 9]])]


In [79]:
arr_v_split

[array([[1, 2, 3]]), array([[4, 5, 6]]), array([[7, 8, 9]])]

In [80]:
arr11 = np.arange(1, 10).reshape(3, 3)
print("Tablica w typie integer:", arr11.dtype)

Tablica w typie integer: int64


In [81]:
# konwersja tablicy na inny typ
# tworzy NOWą tablicę
arr12 = arr11.astype(float)
print("Zmieniony typ na:", arr12.dtype)

Zmieniony typ na: float64


In [82]:
# zmiana ndarray na typy pythonowe
list1 = arr1.tolist()
print("Lista pythonowa:", list1)
print("Typ listy:", type(list1))

Lista pythonowa: [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
Typ listy: <class 'list'>


copy() - kopia tablicy

In [83]:
arr13 = np.arange(1, 5).reshape(2, 2)
print(arr13)

[[1 2]
 [3 4]]


In [84]:
arr_copy = arr13.copy()  # kopia głeboka
arr_view = arr13.view()  # widok
arr_no_copy = arr13

In [86]:
print("Pierwotna tablica:", id(arr13))
print("Kopia głęboka:", id(arr_copy))
print("Kopia płytka (widok)", id(arr_view))
print("Referencja:", id(arr_no_copy))

Pierwotna tablica: 2107137525872
Kopia głęboka: 2107137526256
Kopia płytka (widok) 2107137526352
Referencja: 2107137525872


In [87]:
arr13[1] = [99, 100]

In [88]:
print("Widok:", arr_view)  # widok widzi zmiane

Widok: [[  1   2]
 [ 99 100]]


In [89]:
print("Kopia:", arr_copy)  # w kopi nie ma zmiany

Kopia: [[1 2]
 [3 4]]


In [90]:
arr14 = np.arange(0, 10)
print(arr14)

[0 1 2 3 4 5 6 7 8 9]


In [91]:
print(arr14[3:6])

[3 4 5]


In [92]:
print(arr14[2:7:2])  # start:stop:krok

[2 4 6]


In [94]:
# generowanie danych z krokiem
arr15 = np.arange(21, 41, 2)  # z prawej zbiór otwarty
print(arr15)

[21 23 25 27 29 31 33 35 37 39]


In [95]:
# filtrowanie danych
print(arr15[arr15 > 30])  # wyciągamy większe od 30

[31 33 35 37 39]


In [96]:
arr16 = np.arange(1, 21).reshape(5, 4)
print(arr16)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]]


In [97]:
print(arr16[1:3, [1, 2]])

[[ 6  7]
 [10 11]]


In [99]:
slicer = [1, 2]  #oznacza kolumny do wycięcia

In [100]:
arr17 = np.arange(1, 5).reshape(2, 2)
print(arr17)

[[1 2]
 [3 4]]


In [104]:
arr18 = np.arange(5,9).reshape(2,2)
print(arr18)

[[5 6]
 [7 8]]


In [105]:
print(arr17 + arr18)

[[ 6  8]
 [10 12]]
